const {test}=require('node:test');const assert=require('node:assert/strict');
const s=require('../../src/services/orderProcurement');
const item=(state,quantity=1)=>({name:'Pièce',sku:'A',quantity,procurement:{state,supplier:'Fournisseur A',orderedOn:'2026-09-01',expectedOn:'2026-09-08'}});
test('une ancienne commande ne suppose aucun stock disponible',()=>{const result=s.summarize({status:'paid',items:[{name:'Pièce',quantity:2}]});assert.equal(result.ready,false);assert.equal(result.next,'Vérifier le stock');assert.equal(result.total,2);});
test('toutes les quantités sont requises, avec plusieurs fournisseurs',()=>{const order={status:'paid',items:[item('in_stock',2),item('ordered')]};assert.equal(s.summarize(order).available,2);assert.equal(s.summarize(order).ready,false);order.items[1].procurement.state='received';assert.equal(s.summarize(order).ready,true);});
test('pas de prête à expédier avant paiement ou clonage, ni après expédition',()=>{for(const status of ['pending_payment','shipped','delivered','cancelled','refunded','draft'])assert.equal(s.summarize({status,items:[item('received')]}).ready,false);assert.equal(s.summarize({status:'paid',orderType:'exchange_cloning',cloningStatus:'cloning_in_progress',items:[item('received')]}).ready,false);assert.equal(s.summarize({status:'paid',items:[]}).ready,false);});
test('les dates de retard sont évaluées au jour, la réception supprime le retard fournisseur',()=>{const order={status:'paid',customerPromisedOn:'2026-09-10',items:[item('ordered')]};assert.equal(s.summarize(order,'2026-09-10').customerLate,false);assert.equal(s.summarize(order,'2026-09-11').customerLate,true);assert.equal(s.summarize(order,'2026-09-08').supplierLate,false);order.items[0].procurement.state='received';assert.equal(s.summarize(order,'2026-09-11').supplierLate,false);});
test('validation des dates, statuts et fournisseur requis',()=>{const order={items:[item('unchecked')]};const body={revision:0,signature:s.itemSignature(order.items),customerPromisedOn:'',lines:[{index:0,state:'ordered',supplier:'A',orderedOn:'2026-09-01',expectedOn:'2026-09-12'}]};assert.equal(s.validateUpdate(body,order).lines[0].supplier,'A');for(const date of ['2026-02-30','2026-13-01','demain'])assert.throws(()=>s.validateUpdate({...body,customerPromisedOn:date},order));assert.throws(()=>s.validateUpdate({...body,lines:[{...body.lines[0],supplier:''}]},order));assert.throws(()=>s.validateUpdate({...body,lines:[{...body.lines[0],state:'__proto__'}]},order));});
test('la signature détecte une modification de quantité ou un réordonnancement',()=>{const items=[item('unchecked'),{...item('unchecked'),sku:'B'}];assert.notEqual(s.itemSignature(items),s.itemSignature([...items].reverse()));assert.notEqual(s.itemSignature(items),s.itemSignature([{...items[0],quantity:2},items[1]]));});
